steps:
  - id: upgrade
    action: upgrade
    version_target: "1.7"

  - id: add declared licence
    action: merge
    target: $.metadata.component.licenses
    value: '[{"expression": "EUPL-1.2 OR AGPL-3.0", "acknowledgement": "declared"}]'

  - id: add author
    action: merge
    target: $.metadata.component.authors
    value: '[{"name": "Jean-Baptiste NAHAN", "email":"jean-baptiste@code-rhapsodie.fr"}]'

  - id: add manufacturer
    action: merge
    target: $.metadata.component.manufacturer
    value: '{"name": "Code Rhapsodie", "url":["https://www.code-rhapsodie.fr"]}'

